export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILD = 'FETCH_ARTICLES_FAILD';

export const FETCH_FEED_ARTICLES_REQUEST = 'FETCH_FEED_ARTICLES_REQUEST';
export const FETCH_FEED_ARTICLES_SUCCESS = 'FETCH_FEED_ARTICLES_SUCCESS';
export const FETCH_FEED_ARTICLES_FAILD = 'FETCH_FEED_ARTICLES_FAILD';

export const FILLTER_ARTICLES_AUTHOR_REQUEST = 'FILLTER_ARTICLES_AUTHOR_REQUEST';
export const FILLTER_ARTICLES_AUTHOR_SUCCESS = 'FILLTER_ARTICLES_AUTHOR_SUCCESS';
export const FILLTER_ARTICLES_AUTHOR_FAILD = 'FILLTER_ARTICLES_AUTHOR_FAILD';

export const FILLTER_ARTICLES_FAVORITED_REQUEST = 'FILLTER_ARTICLES_FAVORITED_REQUEST';
export const FILLTER_ARTICLES_FAVORITED_SUCCESS = 'FILLTER_ARTICLES_FAVORITED_SUCCESS';
export const FILLTER_ARTICLES_FAVORITED_FAILD = 'FILLTER_ARTICLES_FAVORITED_FAILD';

export const FILLTER_ARTICLES_TAGS_REQUEST = 'FILLTER_ARTICLES_TAGS_REQUEST';
export const FILLTER_ARTICLES_TAGS_SUCCESS = 'FILLTER_ARTICLES_TAGS_SUCCESS';
export const FILLTER_ARTICLES_TAGS_FAILD = 'FILLTER_ARTICLES_TAGS_FAILD';




