export const FETCH_ARTICLES_DETAIL_REQUEST = 'FETCH_ARTICLES_DETAIL_REQUEST';
export const FETCH_ARTICLES_DETAIL_SUCCESS = 'FETCH_ARTICLES_DETAIL_SUCCESS';
export const FETCH_ARTICLES_DETAIL_FAILD = 'FETCH_ARTICLES_DETAIL_FAILD';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILD = 'DELETE_ARTICLE_FAILD';

export const FAVORITE_ARTICLE_REQUEST = 'FAVORITE_ARTICLE_REQUEST';
export const UNFAVORITE_ARTICLE_REQUEST = 'UNFAVORITE_ARTICLE_REQUEST';