export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILD = 'ADD_COMMENT_FAILD';

export const DELETE_COMMNET_REQUEST = 'DELETE_COMMNET_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILD = 'DELETE_COMMENT_FAILD';

