export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';

export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';

export const FETCH_TAGS_FAILD = 'FETCH_TAGS_FAILD';

export const CHOOSE_CURRENT_TAG = 'CHOOSE_CURRENT_TAG';



